### ISSUE TITLE
Can't seem to make it work

### ISSUE THREAD

**Issue by antoine-delh** [fjaros/cleangroupassigns#1] opened 2020-05-01 12:20 UTC
Hi there !

Been looking for an addon that does this, thanks! I want to try as a priest to spam Prayer of Healing and swapping groups on the fly. 

However the addon tells me I cannot make rearrangements as I am not part of the raid (even though I'm raid leader). Also cannot move people around... See screenshot for details.

Any idea what's happening ?
![Annotation 2020-05-01 141907](https://user-images.githubusercontent.com/64642559/80804906-ddd11f80-8bb6-11ea-9f40-948a6817429c.png)

**Comment by fjaros** [comment] 2020-05-01 14:58
Hi! Can you send me a screenshot of your regular blizzard raid window, and another one of what happens if you click copy current raid?

**Comment by antoine-delh** [comment] 2020-05-02 12:05
Of course! Basically it shows the other player but I can't move them around or anything. At some point when there was 3 players I could kind of move one around but it was buggy (forgot to screen cap though). I deactivated all addons but this one to prevent them from messing it up, but still same result... Tell me if I can provide anything else!

![Annotation 2020-05-02 140032](https://user-images.githubusercontent.com/64642559/80863580-b729ec00-8c7d-11ea-90dc-6e853590ed1f.png)
![Annotation 2020-05-02 140107](https://user-images.githubusercontent.com/64642559/80863582-b98c4600-8c7d-11ea-99e4-62c58a99005e.png)
![Annotation 2020-05-02 140145](https://user-images.githubusercontent.com/64642559/80863584-bb560980-8c7d-11ea-9ae1-3e142313b4b2.png)

**Comment by fjaros** [comment] 2020-05-02 17:26
thanks! The issue is due to your french localization. The addon expects class strings to be in english (Priest instead of Prêtre) . i will try to make it language agnostic :)

**Comment by fjaros** [comment] 2020-05-02 17:55
Fixed in https://github.com/fjaros/cleangroupassigns/commit/cd1a0a2451a08e0d0fabee8055e5c4de49b40d01 . Update is live on curseforge.

**Closed as completed by fjaros** 2020-05-02 17:55 UTC

**Comment by antoine-delh** [comment] 2020-05-02 18:34
Excellent, seems to be working now ;)

Thanks !
